### PR TITLE
Upgrade dashboard / decl. widget releases

### PR DESCRIPTION
**Pull request by parente**
- Point to new jupyter/design UX survey SHA for ~~0.4.5 decl widget compat~~ 0.5.0 decl widget compat

### CODE REVIEW

**Comment by parente** [comment]
@lbustelo Same choice as the binder one.

**Comment by rgbkrk** [comment]
Cool, how's this been going?

**Comment by parente** [comment]
Which part?

EDIT: what the heck was that paste?!

**Comment by rgbkrk** [comment]
Running a tmpnb, demoing these.

**Comment by parente** [comment]
Has been going fine. Is still around and kicking. People using it from time to time. 

http://jupyter.cloudet.xyz

The dashboard of the UX survey results is there from the dev meeting as sort of the uber-example. Many more too.

**Comment by parente** [comment]
@peller I tried the notebook + widget in jupyter/design#26 in this image, but clicking a bar in the explorer plot shows no random selection of responses.

**Comment by parente** [comment]
Fixed by building the image anew. Not sure what happened there. Probably fatigue.

**Comment by parente** [comment]
This can go in. Tested by deploying to jupyter.cloudet.xyz and running a bunch of the examples.

**Comment by lbustelo** [comment]
LGTM

**Pull request merged**
