### PR TITLE
Add UX survey report-dashboard

### PR DESCRIPTION
**Pull request by parente**
- Include notebooks from jupyter/design
- Include dashboard bundle for buildtime deployment
- Bump prereqs

### CODE REVIEW

**Comment by parente** [comment]
Merge after successful deployment, pending jupyter/tmpnb#229.

**Comment by parente** [comment]
Waiting on https://hub.docker.com/r/jupyter/tmpnb/builds/ to build the latest tmpnb with the fix above so that I can update the SHA in the Makefile.

**Comment by parente** [comment]
All set!

**Comment by jtyberg** [comment]
Nice work.  I like how it turned out.

**Comment by jtyberg** [comment]
Nice work. I like how it turned out.

**Pull request merged**
